#!/usr/bin/env bash

PROTECTED_BRANCH='master'
CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ ${PROTECTED_BRANCH} = ${CURRENT_BRANCH} ]]; then
    exec < /dev/tty
        while true; do
            read -p "You're about to commit to master, want some bacon? [y|n]" ANSWER
            case ${ANSWER} in
                [Yy]* ) exit 0;; # tells git to continue normally
                [Nn]* ) exit 1;; # tells git to abort operation
            esac
        done
else
    exit 0 # push will execute
fi
