#!/bin/sh

# thanks for https://github.com/hrules6872

MASTER='refs/heads/master'

if git symbolic-ref HEAD | grep ${MASTER} >/dev/null; then
    exec < /dev/tty
    while true; do
        read -p "You're about to commit to master, want some bacon? [y|n]" ANSWER
        case ${ANSWER} in
            [Yy]* ) exit 0;; # commit
            [Nn]* ) exit 1;; # do nothing
        esac
    done
fi

exit 0 # commit
