#!/usr/bin/env bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]; then
    exec < /dev/tty
        while true; do
            read -p "You're about to commit to master, want some bacon? [y|n]" yn
            case $yn in
                [Yy]* ) exit 0;; # tells git to continue normally
                [Nn]* ) exit 1;; # tells git to abort operation
            esac
        done
else
    exit 0 # push will execute
fi